### ISSUE TITLE
Is there any possibility to do deep orderby?

### ISSUE THREAD

**Issue by sivaecekrr** [aykutkardas/Json-Function#10]
Is there any possibility to do deep orderby?
`
const data = [{
    id: 3,
    userId: 2,
    title: "delectus aut autem",
    metadata: {field1: 'bb', field2: 'btest'}
  },
  {
    id: 2,
    userId: 1,
    title: "lorem ipsum",
    metadata: {field1: 'aa', field2: 'atest'}
  }];
`
`
orderBy(data, "metadata.field1", "ASC");
`

Its a awesome library, which reduces most of my time and code. 👍 
Thank you in advance!

**Comment by aykutkardas** [comment]
In fact, this is possible and a good request.

I will handle this as soon as possible. @sivaecekrr

**Comment by aykutkardas** [comment]
Now available with v1.8.25. Please check. @sivaecekrr 

```js
orderBy(data, "user.firstname", "DESC", { deep: true });
```

**Comment by sivaecekrr** [comment]
@aykutkardas Thank you so much!

Seems to be working, but getting error on 4th parameter, sample in link below. 

https://stackblitz.com/edit/typescript-cjkpns?file=index.ts

**Comment by aykutkardas** [comment]
> @aykutkardas Thank you so much!
> 
> Seems to be working, but getting error on 4th parameter, sample in link below.
> 
> https://stackblitz.com/edit/typescript-cjkpns?file=index.ts

I did solved. **v.1.8.26**

I'm glad this package is useful for you.

**Comment by vapp-project** [comment]
@aykutkardas ASC is working fine but DESC is not working in v.1.8.26

**Comment by vapp-project** [comment]
@aykutkardas console.log(JsonFunction.orderBy("metadata.field1", "ASC", { deep: true }).get(data));

**Comment by aykutkardas** [comment]
> @aykutkardas Both ASC & DESC is not working in v.1.8.26

I'm checking. I will release a new version with more tests soon.

**Comment by aykutkardas** [comment]
> @aykutkardas Both ASC & DESC is not working in v.1.8.26

**Fixed** v.1.8.27

**Sample:** https://codesandbox.io/s/recursing-moore-zid6t
