### ISSUE TITLE
Getting undefined error when field is missing for wh.in condition

### ISSUE THREAD

**Issue by pradeep-nagarajan** [aykutkardas/Json-Function#11]
Getting the below error when field name is missing or value is null when we use wh.in(). But the same error not occurring to wh.eq()

Uncaught (in promise): TypeError: Cannot read property 'includes' of undefined

**Comment by aykutkardas** [comment]
> Getting the below error when field name is missing or value is null when we use wh.in(). But the same error not occurring to wh.eq()
> 
> Uncaught (in promise): TypeError: Cannot read property 'includes' of undefined

Can you give an example in your code?

**Comment by pradeep-nagarajan** [comment]
E.g.:

import {where} from "json-function";

const data = [
  {
    id: 3,
    userId: 2,
    title: "delectus aut autem",
    metadata: { field11: "cc", field2: "ctest" }
  },
  {
    id: 2,
    userId: 1,
    title: "lorem ipsum",
    metadata: { field1: "aa", field2: "atest" }
  },
  {
    id: 1,
    userId: 1,
    title: "lorem ipsum",
    metadata: { field1: "bb", field2: "btest" }
  }
];

Both the below cases throw error,

console.log(where(data, (wh) => ({'metadata.field1' : wh.in('aa')}), {deep: true}));
console.log(where(data, (wh) => ({'metadata.field12' : wh.in('aa')}), {deep: true}));

**Comment by aykutkardas** [comment]
Sample: https://codesandbox.io/s/practical-pond-rxbr9

```js
const result = where(
  data,
  wh => ({
    "metadata.field1": wh.in("b")
  }),
  { deep: true }
);
```

I solved them with v.1.8.28. @pradeep-nagarajan
