### ISSUE TITLE
Is it possible to provide wh.inArray(['ABC','XYZ']) and wh.inArray([21,22])?

### ISSUE THREAD

**Issue by pradeep-nagarajan** [aykutkardas/Json-Function#12]
Is it possible to provide a functionality like wh.inArray(['ABC','XYZ']) and wh.inArray([21,22]) and .notInArray also?

**Comment by pradeep-nagarajan** [comment]
one more request, is this possible JsonFunction.where((wh) => ( [ {'metaData.field1': 'aa'}, {'metaData.field1': 'bb'} ], {deep:true} ));

**Comment by aykutkardas** [comment]
I can explain the work of **"wh.in"** as follows. @pradeep-nagarajan 

```js
const data = [
   {
       id: 1,
       metaData: {
           field1: "bobby",
           field2: [1, 2, "a", "b"]
       }
   }
];

where(data, (wh) => ({
    "metaData.field1": wh.in("bb"),
    "metaData.field2": wh.in("a")
  }), 
  { deep: true }
);
```
When you do this, **"metaData.field1"** value is retrieved and checks if it contains the specified value.

```js
"bobby".includes("bb");

[1, 2, "a", "b"].includes("a");
```

**Comment by pradeep-nagarajan** [comment]
Ok, I am looking for other way,

const data = [
   {
       id: 1,
       metaData: {
           field1: "bobby",
           field2: 1
       }
   }
];

"metaData.field1": wh.in(['bobby','adam'])
"metaData.field2": wh.in([1,2,3,4])

Just like RDBMS IN condition

**Comment by aykutkardas** [comment]
I understood what you wanted, actually a kind of **"oneOf"** you want. It looks like a good idea. I think I can do this. When it is finished it will look like this. @pradeep-nagarajan 

```js
where(data, (wh) => ({
    "metaData.field1": wh.oneOf(["bobby", "adam"]),
  }), 
  { deep: true }
);
```

**Comment by aykutkardas** [comment]
It is now available. Please try **v.1.8.29.**

```js
where(data, (wh) => ({
    "metaData.field1": wh.oneOf(["bobby", "adam"]),
  }), 
  { deep: true }
);
```
