### ISSUE TITLE
Any plans to provide OR condition is this possible JsonFunction.where with deep:true?

### ISSUE THREAD

**Issue by pradeep-nagarajan** [aykutkardas/Json-Function#13]
Any plans to provide OR condition in JsonFunction.where((wh) => ...) with deep:true?

const data = [ { id: 1, metaData: { field1: "bobby",  field2: 2  }  }];

is this possible JsonFunction.where((wh) => ( [ {'metaData.field1': 'aa'}, {'metaData.field2': 2} ], {deep:true} ));

Note: why do we need to pass {deep: true} in where, orderBy etc? Can't we find it based on the key value, like if it has dot (e.g. metaData.field1) then enable deep automatically?

**Comment by aykutkardas** [comment]
> Note: why do we need to pass {deep: true} in where, orderBy etc? Can't we find it based on the key value, like if it has dot (e.g. metaData.field1) then enable deep automatically?

I think about the "deep" option having the "true" value by default. Although there is a low probability, sometimes there may be data such as the following. @pradeep-nagarajan 

```json
{
  "firstname": "John",
  "lastname": "Doe",
  "address.city": "New York"
}
```

**Comment by aykutkardas** [comment]
> is this possible JsonFunction.where((wh) => ( [ {'metaData.field1': 'aa'}, {'metaData.field2': 2} ], {deep:true} ));

In fact, this should be possible. I remember doing this in other functions. I will test if it works here. If it's missing or wrong, I'll handle this. @pradeep-nagarajan 

```js
JsonFunction.where((wh) => ([{ "metaData.field1": "aa" }, { "metaData.field2": 2 }], { deep: true }));
```

**Comment by aykutkardas** [comment]
![Screenshot from 2020-05-10 03-47-47](https://user-images.githubusercontent.com/7966133/81488408-1638c380-9271-11ea-93b8-19d495166e43.png)

This can be done without using the wh tool. @pradeep-nagarajan 

```js
JsonFunction.where([{ "metaData.field1": "aa" }, { "metaData.field2": 2 }], { deep: true }).get(data);
```

You can check more examples.
https://nj0ql.csb.app/

**Comment by pradeep-nagarajan** [comment]
Sorry I missed some details, 

JsonFunction.where((wh) => ( [ {'metaData.field1': wh.in('bb')}, {'metaData.field2': wh.gt(2)} ], {deep:true} ));

**Comment by aykutkardas** [comment]
I have detected some problems for the where function. I will make some improvements and corrections for the use of advanced where function tomorrow. @pradeep-nagarajan

**Comment by aykutkardas** [comment]
For now, I will not do such a thing. I fixed some bugs. Soon I can change the default value of the "deep" option to "true". Thanks for your suggestion. @pradeep-nagarajan
