### ISSUE TITLE
Performance issue in where with 40k objects

### ISSUE THREAD

**Issue by pradeep-nagarajan** [aykutkardas/Json-Function#16]
There is a performance issue when we use wh.in('') on array which has 40k objects in it. It takes 7 seconds to respond.

**Comment by aykutkardas** [comment]
How long will it take when you try to do the same with Pure Javascript? @pradeep-nagarajan 

It may be more accurate to use the methods at its source to filter such a large amount of data. For example, SQL, NoSQL, ElasticSearch etc.

**Comment by pradeep-nagarajan** [comment]
Javascript is slow, but lodash able to filter faster

**Comment by eskiel777** [comment]
40k ?  -.- 
 go to ElasticSearch

**Comment by pradeep-nagarajan** [comment]
I went to alasql which supports 100k. Thanks for your support.
