### ISSUE TITLE
Select & Schema

### ISSUE THREAD

**Issue by absolux** [aykutkardas/Json-Function#17]
Hi,

I've read the source code, and have noticed that `select` is a simpler form of `schema`, where :

```ts
'fieldname' => { "fieldname": "fieldname" }

['field1', 'field2', ...] => { "field1": "field1", "field2": "field2", ... }
```

IMO, it needs some refactoring !!

**Comment by aykutkardas** [comment]
> Hi,
> 
> I've read the source code, and have noticed that `select` is a simpler form of `schema`, where :
> 
> ```ts
> 'fieldname' => { "fieldname": "fieldname" }
> 
> ['field1', 'field2', ...] => { "field1": "field1", "field2": "field2", ... }
> ```
> 
> IMO, it needs some refactoring !!

Can you elaborate on this a little more?

**Comment by absolux** [comment]
`schema` can return the same result as `select`, here is an example :

```ts
select(data, ["firstname", "lastname"])
```
or 
```ts
schema(data, {
  "firstname": "firstname",
  "lastname": "lastname"
})
```
will both return the same data

```js
[
  {
    firstname: "John",
    lastname: "Doe",
  },
  {
    firstname: "Johnny",
    lastname: "Doe",
  }
]
```
IMO, only one function suffice, like the `select` command in SQL.

**Comment by aykutkardas** [comment]
Two different methods are used for different jobs. It is not correct to reduce them to a single method. @absolux
