### ISSUE TITLE
[PERF] too many loops inside where

### ISSUE THREAD

**Issue by absolux** [aykutkardas/Json-Function#18]
Hi,

I've noticed a performance problem for `where` utility. There are many loops :
* a loop to add `UNIQUE_IDX_KEY` for each query object https://github.com/aykutkardas/Json-Function/blob/032bc2e6c8fdf1f27da115d22f00a6fe4907f71b/src/package/where/index.ts#L53-L58
* a loop to filter data https://github.com/aykutkardas/Json-Function/blob/032bc2e6c8fdf1f27da115d22f00a6fe4907f71b/src/package/where/index.ts#L61-L74
* a loop to contruct the result array https://github.com/aykutkardas/Json-Function/blob/032bc2e6c8fdf1f27da115d22f00a6fe4907f71b/src/package/where/index.ts#L77-L81
* a loop to remove `UNIQUE_IDX_KEY` from the result array https://github.com/aykutkardas/Json-Function/blob/032bc2e6c8fdf1f27da115d22f00a6fe4907f71b/src/package/where/index.ts#L84-L87

IMO, you only need 1 loop to filter the data and return the result

**Comment by aykutkardas** [comment]
You are right, I am aware of that. I have a few ideas to optimize this quite a bit. I will pay attention to your suggestions.

Thank you for feedback. @absolux
