### ISSUE TITLE
[PERF] processes priority order

### ISSUE THREAD

**Issue by absolux** [aykutkardas/Json-Function#19]
Hi,

In `JsonFunction` class, the commands are executed in the definition order, not order of priority.

For example in this code, the order is `select -> where -> orderBy -> limit`
```js
JsonFunction
  .select(["title", "completed"])
  .where({ owner: "John" })
  .orderBy("title")
  .limit(2)
```
but the priority order will be `where -> orderBy -> limit -> select`

`select` and `schema` are the lesser priority command, in case `where` returns nothing, `select` should process nothing too.

**Comment by aykutkardas** [comment]
I've been thinking about it these days. I will definitely evaluate this suggestion. I am planning my time to make some improvements.

Thank you @absolux
