### ISSUE TITLE
Module not found: Error: Can't resolve 'json-function'

### ISSUE THREAD

**Issue by sivaecekrr** [aykutkardas/Json-Function#7]
When using the latest version (1.8.16) getting Module not found: Error: Can't resolve 'json-function' issues.
`import JsonFunction from 'json-function';`
`import { where } from 'json-function';`
Tries to import in both ways but no luck. But works in version 1.8.14. Anything i am missing here.

Thank You!

**Comment by aykutkardas** [comment]
Ouch. I'll handle this tomorrow.  Thank you for reporting. @sivaecekrr

**Comment by aykutkardas** [comment]
This issue has been fixed with this release. v1.8.18

**Comment by sivaecekrr** [comment]
Thanks for quick fix. Appreciate it. Its works fine with v1.8.18.
