### ISSUE TITLE
Not able import and use search function

### ISSUE THREAD

**Issue by sivaecekrr** [aykutkardas/Json-Function#8]
Not able import and use search function. Also documentation link not available.

https://worn.gitbook.io/json-function/functions/search

Version: 1.8.18

**Comment by aykutkardas** [comment]
You are right about the document. I will handle this as soon as possible. But you shouldn't have a problem with importing.

Sample:
https://codesandbox.io/s/determined-benz-kw58o?file=/src/index.js

Can you explain the problem a little more?

**Comment by sivaecekrr** [comment]
I am trying to use as below which gives me a error. But other function works with same import.

import * as JsonFunction from 'json-function';

JsonFunction.search(...)

**Comment by aykutkardas** [comment]
Currently, the search function cannot be used as JsonFunction.search. It can only be imported.

These are not the same.

```js
import JF from 'json-function';
import { search } from 'json-function';

JF.search !== search
```

Tomorrow, I will deal with such problems with completing the document.

Thank you for reporting this.

**Comment by sivaecekrr** [comment]
Thank you!

One more question, is it possible to do wildcard filter using where function like below. We tried but not working. Any suggestion.

`where(data, (wh) => [{ userId: wh.eq(1), completed: wh.eq(true) }, { userId: wh.eq(2), completed: wh.eq(false) }], {deep: true}); `

**Comment by aykutkardas** [comment]
You are right I created a issue https://github.com/aykutkardas/Json-Function/issues/9 for this.

**Comment by aykutkardas** [comment]
This issue has been fixed with this release. v1.8.22
